  repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.7.0
      hooks:
        - id: isort
          args: [--profile,  'black']

    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
        - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
        - id: flake8

    - repo: https://github.com/iterative/dvc
      rev: 2.0.5
      hooks:
        - id: dvc-pre-commit
          language_version: python3
          stages:
            - commit
