name: dummy_workflow_to_learn_github_actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run_pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.3'
      - run: pwd
      - run: ls
      - run: pip install poetry==1.2.0
      - run: poetry install
      - run: poetry run pre-commit install
      - run: poetry run pre-commit run --all-files
