name: slack_notif_on_new_version_release
run-name: Notify Slack channel (ds-library-releases) on release new version of library
on: [push]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
jobs:
  # This workflow contains a single job called 'notify_slack'
  notify_slack:
    # only for PR comments that contain 'release patch version'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#ds-library-release-test'
          message: New version release for ${{ github.event.repository.name }} -> ${{ github.event.head_commit.message }}. Commit is ${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}. Commit by ${{github.actor}}
        if: contains(github.event.head_commit.message, 'Bump version')
